name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.3']

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xdebug
          tools: composer

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPUnit
        run: composer tests

      - name: Upload PHPUnit result report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-testdox-php_${{ matrix.php-version }}.txt
          path: var/tests-testdox.txt

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: tests-coverage-php_${{ matrix.php-version }}.txt
          path: var/tests-coverage.txt

      - name: Display PHP version
        run: php -v
